*Exercício 5*
SELECT NOME_CLI, NOME_CID, ANO_FRETE, VALOR_FRETE, PARCELAMENTO_FRETE, PLACA_CAM, NOME_MOT, VALOR_VIAGEM
FROM FRETE
INNER JOIN CLIENTE ON ID_CLI = CLIENTE_ID
INNER JOIN CIDADE ON ID_CID = CIDADE_ID
INNER JOIN CAMINHAO ON ID_CAM = CAMINHAO_ID
INNER JOIN MOTORISTA ON ID_MOT = MOTORISTA_ID
INNER JOIN VIAGEM ON FRETE_ID = ID_FRETE
WHERE ANO_FRETE = 2014