** EXERCÍCIO 2 **
SELECT C.NOME_CLI, CI.NOME_CID, VALOR_FRETE, P.FORMA_PAG
	FROM CLIENTE C
	INNER JOIN FRETE F ON F.CLIENTE_ID = C.ID_CLI
	INNER JOIN CIDADE CI ON CI.ID_CID = C.CID_ID
	INNER JOIN PAGAMENTO P ON P.FRETE_ID = F.ID_FRETE