** EXERCÍCIO 3 **
SELECT F.ID_FRETE, V.VALOR_VIAGEM , M.NOME_MOT
	FROM FRETE F
	INNER JOIN VIAGEM V ON F.ID_FRETE = V.FRETE_ID
	INNER JOIN MOTORISTA M ON M.ID_MOT = F.MOTORISTA_ID
	INNER JOIN CAMINHAO C ON C.ID_CAM = F.CAMINHAO_ID
	WHERE C.ID_CAM = 8